apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: hello-rs-app
spec:
    replicas: 3
    selector:
       matchLabels:
          app: hello-app
    template:
       metadata:
          labels:
             app: hello-app
       spec:
          containers:
          - name: hello-app
            image: schetinnikov/hello-app:v1
            ports:
              - containerPort: 8000
